<a href="https://colab.research.google.com/github/askarbekkk/kyrgyz-embeddings/blob/main/kyrgyz-embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Kyrgyz Information Retrieval — Core Pipeline Setup

This notebook organizes a streamlined, state-of-the-art Kyrgyz Search and Retrieval pipeline. It covers everything from corpus extraction to neural training, Reciprocal Rank Fusion hybrid search, and evaluation metrics visualization.

In [3]:
from google.colab import drive
# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

### Step 1: Dataset Exploration & Validation

Here we load and validate the structure of our core database source (`Zhantas/Cleaned-Kyrgyz_Wikipedia`) to ensure text and titles are present for indexing and query generation.

In [ ]:
# Load the selected dataset cleanly and print the basic metadata
from datasets import load_dataset

print("Loading the chosen dataset: Zhantas/Cleaned-Kyrgyz_Wikipedia...")
clean_wiki_ds = load_dataset("Zhantas/Cleaned-Kyrgyz_Wikipedia", split="train")

print(f"Dataset loaded successfully.")
print(f"Total Wikipedia articles in dataset: {len(clean_wiki_ds)}")
print(f"Columns available: {clean_wiki_ds.column_names}")

Loading the chosen dataset: Zhantas/Cleaned-Kyrgyz_Wikipedia...
Dataset loaded successfully.
Total Wikipedia articles in dataset: 76519
Columns available: ['id', 'url', 'title', 'text']

### Exploring external Kyrgyz datasets on Hugging Face

We look at available Kyrgyz-language datasets (code `ky`) that could serve as additional training or evaluation data for the model.

In [ ]:
from datasets import load_dataset
import pandas as pd

print("Loading demonstration Kyrgyz datasets...")

try:
    # 1. Load Kyrgyz subset from Flores
    flores_ky = load_dataset("facebook/flores", "kir_Cyrl", split="dev")
    print(f"Successfully loaded Flores-101 (KY). Example sentence:")
    print("-", flores_ky[0]["sentence"])
except Exception as e:
    print("Error loading Flores:", e)

try:
    # 2. Load Kyrgyz Wikipedia subset
    mhr_dataset = load_dataset("wikimedia/wikipedia", "20231101.ky", split="train[:100]")
    print(f"\nSuccessfully loaded Wikipedia (KY) subset. Total articles: {len(mhr_dataset)}")
    print("Example article:", mhr_dataset[0]["title"], "|", mhr_dataset[0]["text"][:150])
except Exception as e:
    print("Error loading Wikipedia:", e)

Loading demonstration Kyrgyz datasets...
Error loading Flores: Dataset 'facebook/flores' is a gated dataset on the Hub. You must be authenticated to access it.

KeyboardInterrupt:

### Inspecting the external dataset Zarinaaa/commoncrawl_dataset

We load the dataset from the Hugging Face Hub and print its structure and a few sample records.

In [ ]:
from datasets import load_dataset

print("Loading Zarinaaa/commoncrawl_dataset...")
try:
    # Load Zarinaaa dataset
    cc_dataset = load_dataset("Zarinaaa/commoncrawl_dataset", split="train")

    print("\n=== Successfully Loaded! ===")
    print(f"Number of records: {len(cc_dataset)}")
    print("Available columns:", cc_dataset.column_names)

    # Display first few examples
    print("\nExample data:")
    for i in range(min(3, len(cc_dataset))):
        print(f"\n--- Example {i+1} ---")
        example = cc_dataset[i]
        for col in cc_dataset.column_names:
            val = str(example[col])
            print(f"{col}: {val[:300]}..." if len(val) > 300 else f"{col}: {val}")

except Exception as e:
    print("Failed to load or analyze the dataset:", e)

### Searching Hugging Face for Kyrgyz datasets

We use the `huggingface_hub` API to find datasets related to Kyrgyz and assess whether they are useful for semantic retrieval.

In [ ]:
from huggingface_hub import HfApi
import pandas as pd

api = HfApi()

print("Searching Hugging Face for 'kyrgyz' datasets...")
try:
    # Find datasets that mention Kyrgyz
    datasets = api.list_datasets(search="kyrgyz", sort="downloads", direction=-1, limit=20)

    records = []
    for d in datasets:
        records.append({
            "ID": d.id,
            "Downloads (Month)": getattr(d, "downloads", 0),
            "Likes": getattr(d, "likes", 0),
            "Created At": str(getattr(d, "created_at", "N/A"))[:10]
        })

    df_hf = pd.DataFrame(records)
    if not df_hf.empty:
        display(df_hf)
    else:
        print("No datasets found for 'kyrgyz'.")
except Exception as e:
    print("Search failed:", e)

In [ ]:
!pip install datasets -q
from datasets import load_dataset
import random

ds = load_dataset("Zhantas/Cleaned-Kyrgyz_Wikipedia", split="train")

chunks = []

for art in ds.select(range(5000)):
  for para in art["text"].split("\n"):
    if 200 < len(para) < 800:
      chunks.append({"title": art["title"], "text": para.strip()})

print(len(chunks))
random.seed(42)

for c in random.sample(chunks, 3):
  print(c["title"], "|", c["text"][:200], "\n")

In [ ]:
!pip install openai -q

from openai import OpenAI
from google.colab import userdata, drive
import random, time, json, re, os

drive.mount('/content/drive')
SAVE_PATH = "/content/drive/MyDrive/pairs_raw_v2.json"

client = OpenAI(
    api_key=userdata.get('openrouter_key'),
    base_url="https://openrouter.ai/api/v1",
)
MODEL = "openai/gpt-oss-120b"

PROMPT = """You are given a passage in the Kyrgyz language.

Write ONE short question in Kyrgyz that can be answered using this passage.
The question must sound like something a real person would type into a search engine — natural, specific, and self-contained.

Rules:
- Write the question in Kyrgyz only.
- Do not copy full sentences from the passage.
- Do not reference "the text" or "the passage".
- Return only the question, with no explanation or extra formatting.

Passage:
{text}"""

def clean_text(t):
    """Strip leftover MediaWiki markup and normalize whitespace."""
    t = re.sub(r'thumb\|[^ ]*', '', t)
    t = re.sub(r'\b\d+px\b', '', t)
    t = re.sub(r'(center|right|left)\|', '', t)
    t = re.sub(r'\s+', ' ', t)
    return t.strip()

random.seed(42)
sample = random.sample(chunks, 2500)

# Resume from a previous run: skip passages already processed
if os.path.exists(SAVE_PATH):
    with open(SAVE_PATH, encoding="utf-8") as f:
        pairs = json.load(f)
    done = {p["positive"] for p in pairs}
    print(f"Loaded {len(pairs)} existing pairs, resuming")
else:
    pairs, done = [], set()
    print("Starting from scratch")

def save():
    """Write atomically so an interrupted run cannot corrupt the file."""
    tmp = SAVE_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(pairs, f, ensure_ascii=False, indent=2)
    os.replace(tmp, SAVE_PATH)

try:
    for i, c in enumerate(sample):
        text = clean_text(c["text"])
        if len(text) < 200 or text in done:
            continue

        for attempt in range(3):
            try:
                r = client.chat.completions.create(
                    model=MODEL,
                    messages=[{"role": "user", "content": PROMPT.format(text=text)}],
                )
                pairs.append({
                    "query": r.choices[0].message.content.strip(),
                    "positive": text,
                    "title": c["title"],
                })
                done.add(text)
                break
            except Exception as e:
                print(f"[{i}] attempt {attempt+1}: {e}")
                time.sleep(5 * (attempt + 1))  # back off before retrying

        if len(pairs) % 25 == 0:
            save()
            print(f"i={i}, collected {len(pairs)}, saved")
        time.sleep(0.5)

except KeyboardInterrupt:
    print("Interrupted by user")

finally:
    save()  # always persist, even on crash or manual stop
    print(f"\nTOTAL: {len(pairs)} pairs in {SAVE_PATH}")

In [ ]:
!pip install google-genai groq -q

import json, time, os, re, threading
from concurrent.futures import ThreadPoolExecutor
from google import genai
from groq import Groq
from google.colab import userdata

gemini = genai.Client(api_key=userdata.get('GEMINI_API_KEY'))
groq   = Groq(api_key=userdata.get('groq_apikey'))

# Tried in order; each entry falls back to the next when its quota runs out
BACKENDS = [
    ("gemini", "gemini-3.5-flash-lite"),
    ("gemini", "gemini-3.1-flash-lite"),
    ("gemini", "gemini-3.6-flash"),
    ("groq",   "openai/gpt-oss-20b"),
    ("groq",   "openai/gpt-oss-120b"),
]

RAW_PATH   = "/content/drive/MyDrive/pairs_raw_v2.json"
CLEAN_PATH = "/content/drive/MyDrive/pairs_clean_v2.json"

CHECK = """You are given a passage in Kyrgyz and a question in Kyrgyz.

Answer YES only if ALL of these hold:
1. The question is written in Kyrgyz.
2. The passage contains a complete answer to the question.
3. The question is specific — not a vague or generic prompt.
4. The question makes sense on its own, without seeing the passage.

Otherwise answer NO.

Reply with exactly one word: YES or NO.

Passage:
{text}

Question:
{query}"""

def is_bibliography(t):
    """Reject citation lists and reference entries — not usable prose."""
    return bool(re.search(r'//|Тез\. докл\.|\bС\.\s*\d+-\d+', t)) or t.count('.') > len(t) / 30

with open(RAW_PATH, encoding="utf-8") as f:
    pairs = json.load(f)
print(f"loaded {len(pairs)} raw pairs")

if os.path.exists(CLEAN_PATH):
    with open(CLEAN_PATH, encoding="utf-8") as f:
        clean = json.load(f)
    checked = {p["query"] for p in clean}
    print(f"resuming, {len(clean)} already kept")
else:
    clean, checked = [], set()

lock = threading.Lock()
errors = []
exhausted = set()          # backends whose quota is gone for today
usage = {}                 # how many calls each backend served

def save():
    """Write atomically so an interrupted run cannot corrupt the file."""
    with lock:
        data = list(clean)
    tmp = CLEAN_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    os.replace(tmp, CLEAN_PATH)

def ask(provider, model, prompt):
    if provider == "gemini":
        r = gemini.models.generate_content(model=model, contents=prompt)
        return r.text
    r = groq.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=512,
    )
    return r.choices[0].message.content

def is_daily_quota(e):
    s = str(e).lower()
    return "per day" in s or "tokens per day" in s or "perdayperproject" in s

def check_one(p):
    prompt = CHECK.format(text=p["positive"], query=p["query"])
    for provider, model_name in BACKENDS:
        if (provider, model_name) in exhausted:
            continue
        for attempt in range(3):
            try:
                text = ask(provider, model_name, prompt)
                if text and "YES" in text.strip().upper():
                    with lock:
                        clean.append(p)
                with lock:
                    usage[model_name] = usage.get(model_name, 0) + 1
                return
            except Exception as e:
                if is_daily_quota(e):
                    with lock:
                        if (provider, model_name) not in exhausted:
                            exhausted.add((provider, model_name))
                            print(f"  daily quota gone: {model_name}")
                    break
                time.sleep(20)   # per-minute limit — wait it out
    with lock:
        errors.append(p["query"][:60])

todo = [p for p in pairs
        if p["query"] not in checked and not is_bibliography(p["positive"])]
print(f"to check: {len(todo)}")

with ThreadPoolExecutor(max_workers=3) as ex:
    for n, _ in enumerate(ex.map(check_one, todo)):
        if n % 50 == 0:
            save()
            print(f"{n}/{len(todo)}, kept {len(clean)}, errors {len(errors)}, usage {usage}")

save()
print(f"\n{len(clean)} of {len(pairs)} passed, {len(errors)} failed")
print("usage:", usage)

In [ ]:
import json

with open("/content/drive/MyDrive/pairs_clean_v2.json", encoding="utf-8") as f:
        clean = json.load(f)


with open("/content/drive/MyDrive/pairs_raw_v2.json", encoding="utf-8")  as f:
       pairs = json.load(f)

print(len(clean), len(pairs))

In [ ]:
kept_q = {p["query"] for p in clean}
rejected = [p for p in pairs if p["query"] not in kept_q]

import random
random.seed(1)
for p in random.sample(rejected, 10):
    print("Q:", p["query"])
    print("T:", p["positive"][:200])
    print("---")

In [ ]:
!pip install -U sentence-transformers -q

import json, random
from sentence_transformers import (
    SentenceTransformer, losses,
    SentenceTransformerTrainer, SentenceTransformerTrainingArguments,
)
from sentence_transformers.evaluation import InformationRetrievalEvaluator
from datasets import Dataset

# --- data ---
with open("/content/drive/MyDrive/pairs_raw_v2.json", encoding="utf-8") as f:
    data = json.load(f)

seen, uniq = set(), []
for p in data:
    if p["positive"] not in seen:
        seen.add(p["positive"])
        uniq.append(p)
print(f"{len(uniq)} unique pairs")

random.seed(42)
random.shuffle(uniq)
split = int(len(uniq) * 0.9)
train_pairs, test_pairs = uniq[:split], uniq[split:]
print(len(train_pairs), "train /", len(test_pairs), "test")

# --- evaluation setup: search gold passages among 5000 distractors ---
corpus = {str(i): c["text"] for i, c in enumerate(chunks[:5000])}
queries, relevant = {}, {}
for qi, p in enumerate(test_pairs):
    doc_id = f"gold_{qi}"
    corpus[doc_id] = p["positive"]
    queries[str(qi)] = p["query"]
    relevant[str(qi)] = {doc_id}

evaluator = InformationRetrievalEvaluator(
    queries=queries, corpus=corpus, relevant_docs=relevant, name="ky-v2"
)
print(f"corpus {len(corpus)}, queries {len(queries)}")

# --- baseline ---
model = SentenceTransformer("intfloat/multilingual-e5-base")
before = evaluator(model)
print("BEFORE acc@1:", before['ky-v2_cosine_accuracy@1'])
print("BEFORE nDCG@10:", before['ky-v2_cosine_ndcg@10'])

# --- training ---
train_ds = Dataset.from_dict({
    "anchor":   [p["query"]    for p in train_pairs],
    "positive": [p["positive"] for p in train_pairs],
})

args = SentenceTransformerTrainingArguments(
    output_dir="/content/ky-e5-base-v2",
    num_train_epochs=3,
    per_device_train_batch_size=64,
    learning_rate=3e-5,
    fp16=True,
    logging_steps=5,
)

SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    loss=losses.MultipleNegativesRankingLoss(model),
).train()

after = evaluator(model)
print("\nAFTER acc@1:", after['ky-v2_cosine_accuracy@1'])
print("AFTER nDCG@10:", after['ky-v2_cosine_ndcg@10'])

# --- save ---
model.save("/content/drive/MyDrive/ky-e5-base-v2")
with open("/content/drive/MyDrive/results_v2.json", "w") as f:
    json.dump({"before": before, "after": after,
               "n_train": len(train_pairs), "n_test": len(test_pairs)}, f, indent=2)

### Step 3: Hybrid Search Evaluation (Reciprocal Rank Fusion)

We combine the complementary strengths of lexical search (BM25) and our fine-tuned semantic dense embeddings (ky-e5-base-hardneg) using the classic **Reciprocal Rank Fusion (RRF)** formula.

In [ ]:
!pip install rank_bm25 -q

from rank_bm25 import BM25Okapi
import re, numpy as np

# same corpus as the neural evaluation
doc_ids = list(corpus.keys())
docs    = [corpus[d] for d in doc_ids]

def tok(t):
    return re.findall(r'\w+', t.lower())

bm25 = BM25Okapi([tok(d) for d in docs])

hits1, ndcg = 0, []
for qid, q in queries.items():
    scores = bm25.get_scores(tok(q))
    top10  = np.argsort(scores)[::-1][:10]
    gold   = relevant[qid]

    ranked = [doc_ids[i] for i in top10]
    if ranked[0] in gold:
        hits1 += 1

    # nDCG@10 with a single relevant document
    dcg = 0.0
    for rank, d in enumerate(ranked, start=1):
        if d in gold:
            dcg = 1 / np.log2(rank + 1)
            break
    ndcg.append(dcg)

print(f"BM25 acc@1:   {hits1/len(queries):.4f}")
print(f"BM25 nDCG@10: {np.mean(ndcg):.4f}")
print()
print("e5-base baseline:  0.618 / 0.821")
print("e5-base fine-tuned: 0.641 / 0.843")

In [ ]:
!pip install sentence-transformers==6.0.1 rank_bm25 -q
import numpy as np
import re
from sentence_transformers import SentenceTransformer
from rank_bm25 import BM25Okapi

# 1. Load the best fine-tuned model
print("Loading fine-tuned model...")
ft_model = SentenceTransformer("/content/drive/MyDrive/ky-e5-base-hardneg")

# 2. Prepare corpora and tokenize for BM25
doc_ids = list(corpus.keys())
docs = [corpus[d] for d in doc_ids]

def tokenize(text):
    return re.findall(r'\w+', text.lower())

bm25 = BM25Okapi([tokenize(d) for d in docs])

# 3. Compute vector embeddings
print("Encoding documents and queries...")
doc_embeddings = ft_model.encode(docs, batch_size=64, convert_to_numpy=True, normalize_embeddings=True, show_progress_bar=True)
q_texts = [queries[str(i)] for i in range(len(queries))]
q_embeddings = ft_model.encode(q_texts, batch_size=64, convert_to_numpy=True, normalize_embeddings=True, show_progress_bar=True)
similarity_matrix = q_embeddings @ doc_embeddings.T

# 4. Reciprocal Rank Fusion (RRF) Function
def rrf_search(q_idx, query_text, k=60, top_n=10):
    # BM25 Ranking
    bm25_scores = bm25.get_scores(tokenize(query_text))
    bm25_ranks = np.argsort(bm25_scores)[::-1]

    # Neural Ranking
    neural_scores = similarity_matrix[q_idx]
    neural_ranks = np.argsort(neural_scores)[::-1]

    # Calculate RRF scores
    rrf_scores = {}

    # Keep top-100 candidates from each system for speed
    for rank, doc_idx in enumerate(bm25_ranks[:100], start=1):
        doc_id = doc_ids[doc_idx]
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0.0) + 1.0 / (k + rank)

    for rank, doc_idx in enumerate(neural_ranks[:100], start=1):
        doc_id = doc_ids[doc_idx]
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0.0) + 1.0 / (k + rank)

    # Sort by RRF score
    sorted_docs = sorted(rrf_scores.items(), key=lambda item: item[1], reverse=True)
    return [doc_id for doc_id, score in sorted_docs[:top_n]]

# 5. Evaluate Hybrid Search
hits1, ndcg = 0, []

for qi in range(len(queries)):
    q_id = str(qi)
    q_text = queries[q_id]
    gold = relevant[q_id]

    ranked = rrf_search(qi, q_text, k=60, top_n=10)

    if ranked[0] in gold:
        hits1 += 1

    dcg = 0.0
    for rank, d in enumerate(ranked, start=1):
        if d in gold:
            dcg = 1 / np.log2(rank + 1)
            break
    ndcg.append(dcg)

hybrid_acc = hits1 / len(queries)
hybrid_ndcg = np.mean(ndcg)

print("\n=== HYBRID SEARCH RESULTS ===")
print(f"Hybrid Accuracy@1: {hybrid_acc:.4f}  (Previous max: ~0.645)")
print(f"Hybrid nDCG@10:   {hybrid_ndcg:.4f}  (Previous max: ~0.849)")

## Hard Negative Mining

In-batch negatives are sampled at random, which makes the training task too easy — telling a passage about Manas apart from one about agriculture requires little discrimination. Here we mine *hard* negatives instead: for each query we retrieve the most similar passages using an untuned encoder, exclude the gold passage, and keep the top 3 as negatives. The model is then forced to distinguish between genuinely similar Kyrgyz texts.

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer

# Fresh base model for mining, so negatives aren't biased by the fine-tuned one
miner = SentenceTransformer("intfloat/multilingual-e5-base")

train_texts = [p["positive"] for p in train_pairs]
train_qs    = [p["query"]    for p in train_pairs]

doc_emb = miner.encode(train_texts, batch_size=64, convert_to_numpy=True,
                       normalize_embeddings=True, show_progress_bar=True)
q_emb   = miner.encode(train_qs, batch_size=64, convert_to_numpy=True,
                       normalize_embeddings=True, show_progress_bar=True)

sims = q_emb @ doc_emb.T          # cosine similarity, embeddings are normalized
np.fill_diagonal(sims, -1)        # exclude the gold passage itself

N_NEG = 3
triplets = {"anchor": [], "positive": [], "negative": []}
for i in range(len(train_pairs)):
    top = np.argsort(sims[i])[::-1][:N_NEG]
    for j in top:
        triplets["anchor"].append(train_qs[i])
        triplets["positive"].append(train_texts[i])
        triplets["negative"].append(train_texts[j])

print(len(triplets["anchor"]), "triplets Generated.")

## Training with Hard Negatives

The mined triplets are used to retrain the base encoder from scratch. `MultipleNegativesRankingLoss` detects the explicit `negative` column and uses those passages directly, rather than relying solely on random in-batch negatives. Batch size is reduced to 32 since each example now carries three texts instead of two. The result is compared against the previous best run (0.641 Accuracy@1 / 0.843 nDCG@10) trained on the same data without mined negatives.

In [ ]:
from datasets import Dataset
from sentence_transformers import (
    SentenceTransformer, losses,
    SentenceTransformerTrainer, SentenceTransformerTrainingArguments,
)

triplet_ds = Dataset.from_dict(triplets)

model = SentenceTransformer("intfloat/multilingual-e5-base")
before_hn = evaluator(model)
print("BEFORE acc@1:", before_hn['ky-v2_cosine_accuracy@1'])

args = SentenceTransformerTrainingArguments(
    output_dir="/content/ky-e5-base-hardneg",
    num_train_epochs=1,
    per_device_train_batch_size=32,
    learning_rate=2e-5,
    fp16=True,
    logging_steps=20,
)

SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=triplet_ds,
    # with an explicit negative column, this loss uses it directly
    loss=losses.MultipleNegativesRankingLoss(model),
).train()

after_hn = evaluator(model)
print("\nBEFORE acc@1:", before_hn['ky-v2_cosine_accuracy@1'])
print("AFTER  acc@1:", after_hn['ky-v2_cosine_accuracy@1'])
print("BEFORE nDCG@10:", before_hn['ky-v2_cosine_ndcg@10'])
print("AFTER  nDCG@10:", after_hn['ky-v2_cosine_ndcg@10'])
print("\nprevious best (random negs): 0.641 / 0.843")

In [ ]:
model.save("/content/drive/MyDrive/ky-e5-base-hardneg")

In [ ]:
import torch, gc

for name in ["model", "miner"]:
    if name in globals():
        del globals()[name]
gc.collect()
torch.cuda.empty_cache()
print(f"{torch.cuda.memory_allocated()/1e9:.2f} GB allocated")

## Multi-Seed Comparison

Single runs proved unreliable: identical configurations produced Accuracy@1 between 0.635 and 0.659, a spread of four queries out of 170. Each configuration is therefore retrained across three seeds and reported as mean ± standard deviation, so the comparison reflects a real difference rather than initialization noise.

In [ ]:
import torch, gc, numpy as np
from datasets import Dataset
from sentence_transformers import (
    SentenceTransformer, losses,
    SentenceTransformerTrainer, SentenceTransformerTrainingArguments,
)

pair_ds    = Dataset.from_dict({
    "anchor":   [p["query"]    for p in train_pairs],
    "positive": [p["positive"] for p in train_pairs],
})
triplet_ds = Dataset.from_dict(triplets)

CONFIGS = {
    "random negatives": (pair_ds,    32, 3),   # dataset, batch, epochs
    "hard negatives":   (triplet_ds, 16, 1),
}
SEEDS = [42, 43, 44]

def free():
    gc.collect()
    torch.cuda.empty_cache()

results = {}
for name, (ds, bs, ep) in CONFIGS.items():
    accs, ndcgs = [], []
    for seed in SEEDS:
        free()
        m = SentenceTransformer("intfloat/multilingual-e5-base")
        args = SentenceTransformerTrainingArguments(
            output_dir=f"/content/tmp-{seed}",
            num_train_epochs=ep,
            per_device_train_batch_size=bs,
            learning_rate=2e-5,
            fp16=True,
            seed=seed,
            report_to="none",
            logging_strategy="no",
            save_strategy="no",
        )
        SentenceTransformerTrainer(
            model=m, args=args, train_dataset=ds,
            loss=losses.MultipleNegativesRankingLoss(m),
        ).train()

        r = evaluator(m)
        accs.append(r['ky-v2_cosine_accuracy@1'])
        ndcgs.append(r['ky-v2_cosine_ndcg@10'])
        print(f"{name} seed={seed}: acc@1={accs[-1]:.4f}, nDCG@10={ndcgs[-1]:.4f}")

        del m
        free()

    results[name] = (accs, ndcgs)
    print(f"  → {name}: acc@1 {np.mean(accs):.4f} ± {np.std(accs):.4f}, "
          f"nDCG@10 {np.mean(ndcgs):.4f} ± {np.std(ndcgs):.4f}\n")

print("baseline (no training): 0.618 / 0.821")
for name, (a, n) in results.items():
    print(f"{name:20s} acc@1 {np.mean(a):.4f} ± {np.std(a):.4f}   "
          f"nDCG@10 {np.mean(n):.4f} ± {np.std(n):.4f}")

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# 1. Prepare data for plotting
plot_data = []

# Baseline metrics (fixed values from previous runs)
baseline_acc = 0.6176
baseline_ndcg = 0.8209

# Add Baseline
plot_data.append({"Method": "Baseline", "Metric": "Acc@1", "Value": baseline_acc, "Std": 0})
plot_data.append({"Method": "Baseline", "Metric": "nDCG@10", "Value": baseline_ndcg, "Std": 0})

# Add results from the multi-seed comparison
for name, (accs, ndcgs) in results.items():
    plot_data.append({
        "Method": name.capitalize(),
        "Metric": "Acc@1",
        "Value": np.mean(accs),
        "Std": np.std(accs)
    })
    plot_data.append({
        "Method": name.capitalize(),
        "Metric": "nDCG@10",
        "Value": np.mean(ndcgs),
        "Std": np.std(ndcgs)
    })

df_plot = pd.DataFrame(plot_data)

# 2. Plotting
sns.set_theme(style="whitegrid")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Plot Acc@1
sns.barplot(x="Method", y="Value", data=df_plot[df_plot["Metric"] == "Acc@1"], ax=ax1, palette="Blues_d")
ax1.errorbar(x=range(3), y=df_plot[df_plot["Metric"] == "Acc@1"]["Value"],
             yerr=df_plot[df_plot["Metric"] == "Acc@1"]["Std"], fmt='none', c='black', capsize=5)
ax1.set_title("Accuracy @ 1 Comparison")
ax1.set_ylim(0.6, 0.66)

# Plot nDCG@10
sns.barplot(x="Method", y="Value", data=df_plot[df_plot["Metric"] == "nDCG@10"], ax=ax2, palette="Greens_d")
ax2.errorbar(x=range(3), y=df_plot[df_plot["Metric"] == "nDCG@10"]["Value"],
             yerr=df_plot[df_plot["Metric"] == "nDCG@10"]["Std"], fmt='none', c='black', capsize=5)
ax2.set_title("nDCG @ 10 Comparison")
ax2.set_ylim(0.81, 0.86)

plt.tight_layout()
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Define models to compare
other_models = {
    "E5-small": "intfloat/multilingual-e5-small",
    "E5-large": "intfloat/multilingual-e5-large"
}

comparison_results = []

# 2. Evaluate other E5 sizes
for label, model_name in other_models.items():
    print(f"Evaluating {label}...")
    m = SentenceTransformer(model_name)
    res = evaluator(m)
    comparison_results.append({"Method": label, "Acc@1": res['ky-v2_cosine_accuracy@1'], "nDCG@10": res['ky-v2_cosine_ndcg@10']})

# 3. Add previously calculated baseline and BM25 results
# BM25 results from cell 2XBq6m_a1jIl: 0.6235 / 0.7695
comparison_results.append({"Method": "BM25", "Acc@1": 0.6235, "nDCG@10": 0.7695})

# E5-base baseline (no training)
comparison_results.append({"Method": "E5-base (untuned)", "Acc@1": 0.6176, "nDCG@10": 0.8209})

# E5-base fine-tuned (Hard Negatives mean)
comparison_results.append({"Method": "E5-base (Fine-tuned)", "Acc@1": np.mean(results['hard negatives'][0]), "nDCG@10": np.mean(results['hard negatives'][1])})

# 4. Visualization
df_comp = pd.DataFrame(comparison_results).sort_values("Acc@1")

sns.set_theme(style="whitegrid")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

sns.barplot(x="Method", y="Acc@1", data=df_comp, ax=ax1, palette="magma")
ax1.set_title("Accuracy @ 1: Model Size vs BM25")
ax1.set_ylim(0.5, 0.7)
ax1.tick_params(axis='x', rotation=45)

sns.barplot(x="Method", y="nDCG@10", data=df_comp, ax=ax2, palette="viridis")
ax2.set_title("nDCG @ 10: Model Size vs BM25")
ax2.set_ylim(0.7, 0.9)
ax2.tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

In [ ]:
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sentence_transformers import SentenceTransformer

# 1. Identify fine-tuned models in Drive
drive_path = "/content/drive/MyDrive/"
model_dirs = [d for d in os.listdir(drive_path) if d.startswith("ky-e5-") and os.path.isdir(os.path.join(drive_path, d))]
print(f"Found fine-tuned models: {model_dirs}")

comparison_results = []

# 2. Evaluate each fine-tuned model
for model_folder in model_dirs:
    full_path = os.path.join(drive_path, model_folder)
    print(f"Evaluating fine-tuned model from: {model_folder}...")
    try:
        m = SentenceTransformer(full_path)
        res = evaluator(m)
        comparison_results.append({
            "Method": f"{model_folder} (FT)",
            "Acc@1": res['ky-v2_cosine_accuracy@1'],
            "nDCG@10": res['ky-v2_cosine_ndcg@10'],
            "Category": "Fine-tuned"
        })
        del m
        free()
    except Exception as e:
        print(f"Error loading {model_folder}: {e}")

# 3. Add Baselines for comparison
# Neural Baselines (Untuned)
for label, m_name in {"E5-small (Base)": "intfloat/multilingual-e5-small", "E5-base (Base)": "intfloat/multilingual-e5-base"}.items():
    print(f"Evaluating baseline {label}...")
    m = SentenceTransformer(m_name)
    res = evaluator(m)
    comparison_results.append({"Method": label, "Acc@1": res['ky-v2_cosine_accuracy@1'], "nDCG@10": res['ky-v2_cosine_ndcg@10'], "Category": "Baseline"})
    del m
    free()

# BM25 Lexical Baseline
comparison_results.append({"Method": "BM25", "Acc@1": 0.6235, "nDCG@10": 0.7695, "Category": "Lexical"})

# 4. Visualization
df_comp = pd.DataFrame(comparison_results).sort_values("Acc@1")

sns.set_theme(style="whitegrid")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 7))

sns.barplot(x="Method", y="Acc@1", hue="Category", data=df_comp, ax=ax1)
ax1.set_title("Accuracy @ 1 Comparison")
ax1.set_ylim(0.5, 0.7)
ax1.tick_params(axis='x', rotation=45)

sns.barplot(x="Method", y="nDCG@10", hue="Category", data=df_comp, ax=ax2)
ax2.set_title("nDCG @ 10 Comparison")
ax2.set_ylim(0.7, 0.9)
ax2.tick_params(axis='x', rotation=45)
plt.savefig(SAVE_FOLDER + "cmp.png", dpi=300, bbox_inches='tight')


plt.tight_layout()
plt.show()

## Evaluation fix: gold passages duplicated among distractors

The original evaluation sampled distractors from `chunks[:5000]` while test queries were generated from `random.sample(chunks, 2500)`, so 58 of 170 gold passages also appeared in the corpus under a second id. Retrieving the identical copy first was scored as a miss, which deflated every method (especially Accuracy@1). The cells below remove those duplicates and re-evaluate all methods on the same fixed corpus (also testing E5 `query:` / `passage:` prefixes). Results are saved to `results_fixed_corpus.json`; numbers in earlier cells were computed on the flawed corpus.

In [6]:
# Sanity check: are test gold passages duplicated among the distractors?
!pip install -q "sentence-transformers>=6.0.1" datasets
import os, json, random

if not os.path.exists("/content/drive/MyDrive"):
    from google.colab import drive
    drive.mount('/content/drive')

if "chunks" not in globals():
    from datasets import load_dataset
    ds = load_dataset("Zhantas/Cleaned-Kyrgyz_Wikipedia", split="train")
    chunks = [{"title": a["title"], "text": p.strip()}
              for a in ds.select(range(5000)) for p in a["text"].split("\n")
              if 200 < len(p) < 800]

with open("/content/drive/MyDrive/pairs_raw_v2.json", encoding="utf-8") as f:
    data = json.load(f)
seen, uniq = set(), []
for p in data:
    if p["positive"] not in seen:
        seen.add(p["positive"]); uniq.append(p)
random.seed(42); random.shuffle(uniq)
test_pairs = uniq[int(len(uniq) * 0.9):]

distractors = {c["text"] for c in chunks[:5000]}
norm = lambda t: " ".join(t.split())
distractors_norm = {norm(t) for t in distractors}

exact = sum(p["positive"] in distractors for p in test_pairs)
near = sum(norm(p["positive"]) in distractors_norm for p in test_pairs)
print(f"chunks: {len(chunks)}, test queries: {len(test_pairs)}")
print(f"gold passages also present as distractor: exact {exact}, whitespace-normalized {near}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 740.6/740.6 kB 36.6 MB/s eta 0:00:00
chunks: 14250, test queries: 170
gold passages also present as distractor: exact 56, whitespace-normalized 58

In [7]:
# Re-evaluate on a fixed corpus: gold duplicates removed from distractors, with / without E5 prefixes
!pip install -q rank_bm25
import re, gc, torch, numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from sentence_transformers.sentence_transformer.evaluation import InformationRetrievalEvaluator
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "none")

gold_norm = {norm(p["positive"]) for p in test_pairs}
fixed_corpus = {str(i): c["text"] for i, c in enumerate(chunks[:5000]) if norm(c["text"]) not in gold_norm}
queries, relevant = {}, {}
for qi, p in enumerate(test_pairs):
    fixed_corpus[f"gold_{qi}"] = p["positive"]
    queries[str(qi)] = p["query"]
    relevant[str(qi)] = {f"gold_{qi}"}
print(f"corpus {len(fixed_corpus)}, queries {len(queries)}")

rows = []

# BM25 on the same fixed corpus
tok = lambda t: re.findall(r'\w+', t.lower())
doc_ids = list(fixed_corpus)
bm25 = BM25Okapi([tok(fixed_corpus[d]) for d in doc_ids])
hits1, ndcg = 0, []
for qid, q in queries.items():
    ranked = [doc_ids[i] for i in np.argsort(bm25.get_scores(tok(q)))[::-1][:10]]
    hits1 += ranked[0] in relevant[qid]
    ndcg.append(next((1 / np.log2(r + 1) for r, d in enumerate(ranked, 1) if d in relevant[qid]), 0.0))
rows.append(("BM25", "-", hits1 / len(queries), float(np.mean(ndcg))))
print(f"{'BM25':30s} prefix=-   acc@1={rows[-1][2]:.4f} nDCG@10={rows[-1][3]:.4f}")

def make_eval(prefix):
    kw = {"query_prompt": "query: ", "corpus_prompt": "passage: "} if prefix else {}
    return InformationRetrievalEvaluator(queries=queries, corpus=fixed_corpus,
                                         relevant_docs=relevant, name="fixed", **kw)

MODELS = {
    "e5-base (untuned)": "intfloat/multilingual-e5-base",
    "ky-e5-base-v2 (random negs)": "/content/drive/MyDrive/ky-e5-base-v2",
    "ky-e5-base-hardneg": "/content/drive/MyDrive/ky-e5-base-hardneg",
}
for label, path in MODELS.items():
    if path.startswith("/") and not os.path.exists(path):
        print("skip, not found:", path); continue
    m = SentenceTransformer(path)
    for prefix in (False, True):
        r = make_eval(prefix)(m)
        rows.append((label, "yes" if prefix else "no",
                     r["fixed_cosine_accuracy@1"], r["fixed_cosine_ndcg@10"]))
        print(f"{label:30s} prefix={rows[-1][1]:3s} acc@1={rows[-1][2]:.4f} nDCG@10={rows[-1][3]:.4f}")
    del m; gc.collect(); torch.cuda.empty_cache()

with open("/content/drive/MyDrive/results_fixed_corpus.json", "w") as f:
    json.dump([dict(zip(["method", "prefix", "acc@1", "ndcg@10"], r)) for r in rows], f, indent=2)

GPU: Tesla T4
corpus 5112, queries 170
BM25                           prefix=-   acc@1=0.7294 nDCG@10=0.8108

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/179k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.11GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

e5-base (untuned)              prefix=no  acc@1=0.8765 nDCG@10=0.9212
e5-base (untuned)              prefix=yes acc@1=0.8471 nDCG@10=0.9041

Loading weights:   0%|          | 0/199 [00:03<?, ?it/s]

ky-e5-base-v2 (random negs)    prefix=no  acc@1=0.9059 nDCG@10=0.9441
ky-e5-base-v2 (random negs)    prefix=yes acc@1=0.9000 nDCG@10=0.9425

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

ky-e5-base-hardneg             prefix=no  acc@1=0.9176 nDCG@10=0.9504
ky-e5-base-hardneg             prefix=yes acc@1=0.9235 nDCG@10=0.9521

## Evaluation v3: leak-free and external test sets

The original test set is near its ceiling (untuned E5 already reaches nDCG@10 0.92), is fully synthetic, and shares source articles with the training pairs. Two additional benchmarks:

1. **Belebele (`kir_Cyrl`)** — human-written questions over FLORES passages, used as an external retrieval test.
2. **Held-out Wikipedia test** — queries generated only from articles never used for training (index ≥ 5000), then manually verified by a native speaker.

In [8]:
# Shared evaluation: BM25 + all encoders on one corpus, Accuracy@1 / MRR@10 / nDCG@10
import re, gc, os, json, torch, numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from sentence_transformers.sentence_transformer.evaluation import InformationRetrievalEvaluator

ENCODERS = {
    "e5-base (untuned)": "intfloat/multilingual-e5-base",
    "ky-e5-base-v2 (random negs)": "/content/drive/MyDrive/ky-e5-base-v2",
    "ky-e5-base-hardneg": "/content/drive/MyDrive/ky-e5-base-hardneg",
}
tok = lambda t: re.findall(r'\w+', t.lower())

def bm25_eval(corpus, queries, relevant):
    ids = list(corpus)
    bm25 = BM25Okapi([tok(corpus[d]) for d in ids])
    acc, mrr, ndcg = [], [], []
    for qid, q in queries.items():
        ranked = [ids[i] for i in np.argsort(bm25.get_scores(tok(q)))[::-1][:10]]
        hit = next((r for r, d in enumerate(ranked, 1) if d in relevant[qid]), None)
        acc.append(hit == 1)
        mrr.append(1 / hit if hit else 0.0)
        ndcg.append(1 / np.log2(hit + 1) if hit else 0.0)
    return float(np.mean(acc)), float(np.mean(mrr)), float(np.mean(ndcg))

def evaluate_all(corpus, queries, relevant, name):
    print(f"[{name}] corpus {len(corpus)}, queries {len(queries)}")
    rows = [("BM25", *bm25_eval(corpus, queries, relevant))]
    ev = InformationRetrievalEvaluator(queries=queries, corpus=corpus, relevant_docs=relevant, name=name)
    for label, path in ENCODERS.items():
        m = SentenceTransformer(path)
        r = ev(m)
        rows.append((label, r[f"{name}_cosine_accuracy@1"], r[f"{name}_cosine_mrr@10"], r[f"{name}_cosine_ndcg@10"]))
        del m; gc.collect(); torch.cuda.empty_cache()
    for label, a, m, n in rows:
        print(f"  {label:30s} acc@1={a:.4f}  MRR@10={m:.4f}  nDCG@10={n:.4f}")
    return rows

In [9]:
# Belebele (kir_Cyrl): human-written questions -> find their FLORES passage among passages + Wikipedia distractors
from datasets import load_dataset

bele = load_dataset("facebook/belebele", "kir_Cyrl", split="test")
print(bele)

passages = sorted({ex["flores_passage"] for ex in bele})
pid = {p: f"bele_{i}" for i, p in enumerate(passages)}
bele_corpus = {pid[p]: p for p in passages}
bele_corpus.update({f"wiki_{i}": c["text"] for i, c in enumerate(chunks[:5000])})  # distractors

bele_queries = {str(i): ex["question"] for i, ex in enumerate(bele)}
bele_relevant = {str(i): {pid[ex["flores_passage"]]} for i, ex in enumerate(bele)}

bele_rows = evaluate_all(bele_corpus, bele_queries, bele_relevant, "belebele")
with open("/content/drive/MyDrive/results_belebele.json", "w") as f:
    json.dump([dict(zip(["method", "acc@1", "mrr@10", "ndcg@10"], r)) for r in bele_rows], f, indent=2)

README.md:   0%|          | 0.00/25.5k [00:00<?, ?B/s]

kir_Cyrl.jsonl:   0%|          | 0.00/3.42M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/900 [00:00<?, ? examples/s]

Dataset({
    features: ['link', 'question_number', 'flores_passage', 'question', 'mc_answer1', 'mc_answer2', 'mc_answer3', 'mc_answer4', 'correct_answer_num', 'dialect', 'ds'],
    num_rows: 900
})
[belebele] corpus 5488, queries 900

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

  BM25                           acc@1=0.4844  MRR@10=0.5427  nDCG@10=0.5718
  e5-base (untuned)              acc@1=0.5589  MRR@10=0.6336  nDCG@10=0.6706
  ky-e5-base-v2 (random negs)    acc@1=0.7400  MRR@10=0.7845  nDCG@10=0.8079
  ky-e5-base-hardneg             acc@1=0.7344  MRR@10=0.7855  nDCG@10=0.8106

In [1]:
# Held-out test set: queries generated only from articles never used in training (index >= 5000).
# Half natural questions, half short keyword queries. Resumable; falls back across free-tier backends.
!pip install google-genai groq openai -q
import re, os, json, random, time
from google import genai
from groq import Groq
from openai import OpenAI
from google.colab import userdata
from datasets import load_dataset

if not os.path.exists("/content/drive/MyDrive"):
    from google.colab import drive
    drive.mount('/content/drive')

HELDOUT_PATH = "/content/drive/MyDrive/test_heldout_raw.json"
N_TEST = 500

gemini = genai.Client(api_key=userdata.get('GEMINI_API_KEY'))
groq = Groq(api_key=userdata.get('groq_apikey'))
openrouter = OpenAI(api_key=userdata.get('openrouter_key'), base_url="https://openrouter.ai/api/v1")
BACKENDS = [
    ("gemini",     "gemini-3.5-flash-lite"),
    ("gemini",     "gemini-3.1-flash-lite"),
    ("groq",       "openai/gpt-oss-120b"),
    ("groq",       "openai/gpt-oss-20b"),
    ("openrouter", "google/gemma-4-31b-it:free"),  # free tier: ~50 requests/day
]
dead = set()  # backends out of quota / credits for this run

PROMPTS = {
    "question": """You are given a passage in the Kyrgyz language.

Write ONE short question in Kyrgyz that can be answered using this passage.
It must sound like something a real person would type into a search engine — natural, specific, and self-contained.
Do not copy full sentences from the passage. Do not reference "the text" or "the passage".
Return only the question.

Passage:
{text}""",
    "keywords": """You are given a passage in the Kyrgyz language.

Write ONE short keyword-style search query in Kyrgyz (2-5 words, no question mark) that a person would type to find this passage.
Prefer the key entity plus what the person wants to know about it. Do not copy a whole phrase from the passage.
Return only the query.

Passage:
{text}""",
}

def ask(provider, model, prompt):
    if provider == "gemini":
        return gemini.models.generate_content(model=model, contents=prompt).text
    client = groq if provider == "groq" else openrouter
    r = client.chat.completions.create(model=model, messages=[{"role": "user", "content": prompt}], max_tokens=512)
    return r.choices[0].message.content

def is_fatal(e):
    """Quota/credit/auth errors: retrying the same backend is pointless."""
    s = str(e).lower()
    return any(k in s for k in ("per day", "perday", "402", "401", "403", "insufficient", "api key", "permission"))

def generate(prompt):
    for backend in BACKENDS:
        if backend in dead:
            continue
        for attempt in range(3):
            try:
                text = ask(*backend, prompt)
                if text and text.strip():
                    return text.strip(), backend[1]
            except Exception as e:
                if is_fatal(e):
                    dead.add(backend); print(f"  backend off: {backend[1]}: {str(e)[:120]}"); break
                time.sleep(15)  # per-minute rate limit
    return None, None

def clean_text(t):
    t = re.sub(r'thumb\|[^ ]*', '', t)
    t = re.sub(r'\b\d+px\b', '', t)
    t = re.sub(r'(center|right|left)\|', '', t)
    return re.sub(r'\s+', ' ', t).strip()

wiki = load_dataset("Zhantas/Cleaned-Kyrgyz_Wikipedia", split="train")
heldout_chunks = [{"title": a["title"], "text": clean_text(p)}
                  for a in wiki.select(range(5000, 15000)) for p in a["text"].split("\n")
                  if 200 < len(p) < 800]

# one passage per article, so the test covers many topics
random.seed(7)
random.shuffle(heldout_chunks)
by_title = {}
for c in heldout_chunks:
    by_title.setdefault(c["title"], c)
candidates = list(by_title.values())[:N_TEST]
print(f"held-out paragraphs {len(heldout_chunks)}, articles {len(by_title)}, sampling {len(candidates)}")

test_set = json.load(open(HELDOUT_PATH, encoding="utf-8")) if os.path.exists(HELDOUT_PATH) else []
done = {t["positive"] for t in test_set}
print(f"resuming with {len(test_set)} done")

def save_heldout():
    tmp = HELDOUT_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(test_set, f, ensure_ascii=False, indent=2)
    os.replace(tmp, HELDOUT_PATH)

try:
    for i, c in enumerate(candidates):
        if c["text"] in done:
            continue
        style = "question" if i % 2 == 0 else "keywords"
        query, model_used = generate(PROMPTS[style].format(text=c["text"]))
        if query is None:
            print("all backends exhausted — rerun later to resume"); break
        test_set.append({"id": i, "style": style, "query": query, "positive": c["text"],
                         "title": c["title"], "model": model_used})
        done.add(c["text"])
        if len(test_set) % 25 == 0:
            save_heldout(); print(f"{len(test_set)}/{len(candidates)} saved")
finally:
    save_heldout()
    print(f"TOTAL {len(test_set)} in {HELDOUT_PATH}")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

held-out paragraphs 15981, articles 7323, sampling 500
resuming with 499 done
TOTAL 499 in /content/drive/MyDrive/test_heldout_raw.json

In [7]:
# Build the annotation package (see the annotation guidelines). Files go to MyDrive/annotation/:
#   pilot_taskA.csv            - 30 items labelled by all three annotators
#   taskB_annotator{1,2,3}.csv - write-your-own queries for 200 passages (done BEFORE Task A)
#   taskA_annotator{1,2,3}.csv - validate LLM queries; every non-pilot item goes to exactly two annotators
#   assignments.json           - who got what (for adjudication and agreement)
# Annotators never see which model wrote a query. Annotator 1 is the project author.
# Items shown as worked examples in the guidelines are excluded, so no annotator sees a pre-labelled item.
import random, shutil, pandas as pd

GUIDELINE_EXAMPLE_IDS = {243, 271, 366, 420}
OUT = "/content/drive/MyDrive/annotation"
os.makedirs(OUT, exist_ok=True)
old_review = "/content/drive/MyDrive/test_heldout_review.csv"
if os.path.exists(old_review):  # exported from the mixed-generator set; keep it out of the way
    shutil.move(old_review, "/content/drive/MyDrive/test_heldout_review_OLD_mixed_generators.csv")

items = json.load(open(HELDOUT_PATH, encoding="utf-8"))
assert len({t["model"] for t in items}) == 1, "held-out set must come from one generator"
rng = random.Random(2026)
ids = [t["id"] for t in items if t["id"] not in GUIDELINE_EXAMPLE_IDS]
rng.shuffle(ids)
by_id = {t["id"]: t for t in items}

pilot_ids = ids[:30]
main_ids = ids[30:]
taskb_ids = rng.sample(ids, 200)                      # Task B passages
pairs = [(1, 2), (1, 3), (2, 3)]
taskA = {1: [], 2: [], 3: []}
for k, i in enumerate(main_ids):                      # balanced: each pair gets a third of the items
    for a in pairs[k % 3]:
        taskA[a].append(i)
taskB = {a: taskb_ids[a - 1::3] for a in (1, 2, 3)}  # each passage gets one human query

A_COLS = ["id", "style", "query", "passage", "title", "label", "error_category", "fixed_query", "note"]
def task_a_sheet(id_list, path):
    rows = [{"id": i, "style": by_id[i]["style"], "query": by_id[i]["query"], "passage": by_id[i]["positive"],
             "title": by_id[i]["title"], "label": "", "error_category": "", "fixed_query": "", "note": ""}
            for i in rng.sample(id_list, len(id_list))]
    pd.DataFrame(rows, columns=A_COLS).to_csv(path, index=False, encoding="utf-8-sig")

def task_b_sheet(id_list, path):  # style matches the LLM query for the same passage; the LLM query is not shown
    rows = [{"id": i, "style": by_id[i]["style"], "passage": by_id[i]["positive"], "title": by_id[i]["title"],
             "your_query": "", "note": ""} for i in rng.sample(id_list, len(id_list))]
    pd.DataFrame(rows).to_csv(path, index=False, encoding="utf-8-sig")

task_a_sheet(pilot_ids, f"{OUT}/pilot_taskA.csv")
for a in (1, 2, 3):
    task_a_sheet(taskA[a], f"{OUT}/taskA_annotator{a}.csv")
    task_b_sheet(taskB[a], f"{OUT}/taskB_annotator{a}.csv")
json.dump({"generator": items[0]["model"], "excluded_examples": sorted(GUIDELINE_EXAMPLE_IDS), "pilot": pilot_ids,
           "taskA": taskA, "taskB": taskB}, open(f"{OUT}/assignments.json", "w"), indent=1)

print("items:", len(ids), "| pilot:", len(pilot_ids), "| Task A per annotator:", {a: len(v) for a, v in taskA.items()},
      "| Task B per annotator:", {a: len(v) for a, v in taskB.items()})

items: 495 | pilot: 30 | Task A per annotator: {1: 310, 2: 310, 3: 310} | Task B per annotator: {1: 67, 2: 67, 3: 66}

In [4]:
# Make the held-out set single-generator: regenerate every query not written by TARGET_MODEL
# (same passages, same prompts). Old queries are archived, not deleted. Resumable; run again after quota resets.
# Needs the held-out generation cell above to have run first (gemini client, PROMPTS, save_heldout).
import shutil, collections
TARGET_MODEL = "gemini-3.5-flash-lite"
ARCHIVE_PATH = "/content/drive/MyDrive/test_heldout_raw_mixed_backup.json"

test_set = json.load(open(HELDOUT_PATH, encoding="utf-8"))
if not os.path.exists(ARCHIVE_PATH):
    shutil.copy(HELDOUT_PATH, ARCHIVE_PATH)

def regenerate(prompt, max_waits=10):
    """Wait out per-minute limits; give up only on a daily quota or repeated failures."""
    for _ in range(max_waits):
        try:
            return gemini.models.generate_content(model=TARGET_MODEL, contents=prompt).text
        except Exception as e:
            if "per day" in str(e).lower() or "perday" in str(e).lower():
                raise
            time.sleep(60)
    raise RuntimeError("still rate-limited after waiting")

todo = [t for t in test_set if t["model"] != TARGET_MODEL]
print(f"{len(todo)} queries to regenerate with {TARGET_MODEL}")
for k, t in enumerate(todo, 1):
    try:
        text = regenerate(PROMPTS[t["style"]].format(text=t["positive"]))
    except Exception as e:
        print(f"stopped at {k - 1}/{len(todo)}: {str(e)[:160]}"); break
    if text and text.strip():
        t["query"], t["model"] = text.strip(), TARGET_MODEL
    if k % 25 == 0:
        save_heldout(); print(f"{k}/{len(todo)} saved")
save_heldout()
print(collections.Counter(t["model"] for t in test_set))

202 queries to regenerate with gemini-3.5-flash-lite
25/202 saved
50/202 saved
75/202 saved
100/202 saved
125/202 saved
150/202 saved
175/202 saved
200/202 saved
Counter({'gemini-3.5-flash-lite': 499})

## Zero-shot comparison of multilingual embedding models

Each encoder is used as its model card recommends (built-in query/document prompts where the model defines them; E5 without prefixes, which scored higher on this data). Max sequence length is capped at 512 tokens for all models; passages are ≤ 800 characters, so nothing is truncated in practice.

In [10]:
# Zero-shot comparison: BM25 + multilingual encoders (+ our fine-tuned e5-base) on all test sets.
# Each model: (HF id or path, evaluator prompt kwargs). Models that fail to load (e.g. gated) are skipped.
import gc, json, torch, pandas as pd
from sentence_transformers import SentenceTransformer
from sentence_transformers.sentence_transformer.evaluation import InformationRetrievalEvaluator

# Held-out test (raw, before native-speaker review): gold passages + 5,000 distractors, all from articles >= 5000
heldout = json.load(open("/content/drive/MyDrive/test_heldout_raw.json", encoding="utf-8"))
ho_gold = {norm(t["positive"]) for t in heldout}
ho_corpus = {f"d{i}": c["text"] for i, c in enumerate([c for c in heldout_chunks if norm(c["text"]) not in ho_gold][:5000])}
ho_queries, ho_relevant = {}, {}
for t in heldout:
    ho_corpus[f"g{t['id']}"] = t["positive"]
    ho_queries[str(t["id"])] = t["query"]
    ho_relevant[str(t["id"])] = {f"g{t['id']}"}

ZERO_SHOT = {
    "LaBSE":                 ("sentence-transformers/LaBSE", {}),
    "e5-small":              ("intfloat/multilingual-e5-small", {}),
    "e5-base":               ("intfloat/multilingual-e5-base", {}),
    "e5-large":              ("intfloat/multilingual-e5-large", {}),
    "bge-m3":                ("BAAI/bge-m3", {}),
    "Qwen3-Embedding-0.6B":  ("Qwen/Qwen3-Embedding-0.6B", {"query_prompt_name": "query"}),
    "EmbeddingGemma-300m":   ("google/embeddinggemma-300m", {"query_prompt_name": "query", "corpus_prompt_name": "document"}),
    "ours: e5-base FT (hard negs)": ("/content/drive/MyDrive/ky-e5-base-hardneg", {}),
}

BENCHMARKS = {
    "synthetic_fixed": (fixed_corpus, queries, relevant),
    "heldout_raw": (ho_corpus, ho_queries, ho_relevant),
    "belebele": (bele_corpus, bele_queries, bele_relevant),
}

results = []
for bench, (corpus, qs, rel) in BENCHMARKS.items():
    a, m, n = bm25_eval(corpus, qs, rel)
    results.append({"benchmark": bench, "model": "BM25", "acc@1": a, "mrr@10": m, "ndcg@10": n})
    print(f"{bench:16s} {'BM25':30s} acc@1={a:.4f} nDCG@10={n:.4f}")

for label, (path, prompt_kw) in ZERO_SHOT.items():
    try:
        model = SentenceTransformer(path, model_kwargs={"torch_dtype": torch.float16})
    except Exception as e:
        print(f"skip {label}: {str(e)[:150]}"); continue
    model.max_seq_length = 512
    for bench, (corpus, qs, rel) in BENCHMARKS.items():
        ev = InformationRetrievalEvaluator(queries=qs, corpus=corpus, relevant_docs=rel, name=bench,
                                           batch_size=32, **prompt_kw)
        r = ev(model)
        results.append({"benchmark": bench, "model": label, "acc@1": r[f"{bench}_cosine_accuracy@1"],
                        "mrr@10": r[f"{bench}_cosine_mrr@10"], "ndcg@10": r[f"{bench}_cosine_ndcg@10"]})
        print(f"{bench:16s} {label:30s} acc@1={results[-1]['acc@1']:.4f} nDCG@10={results[-1]['ndcg@10']:.4f}")
    del model; gc.collect(); torch.cuda.empty_cache()
    pd.DataFrame(results).to_csv("/content/drive/MyDrive/results_zero_shot.csv", index=False)  # save as we go

df_zs = pd.DataFrame(results)
display(df_zs.pivot(index="model", columns="benchmark", values="acc@1").round(3))

synthetic_fixed  BM25                           acc@1=0.7294 nDCG@10=0.8108
heldout_raw      BM25                           acc@1=0.6132 nDCG@10=0.7194
belebele         BM25                           acc@1=0.4844 nDCG@10=0.5718

modules.json:   0%|          | 0.00/461 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.02k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/804 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.88GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/397 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/5.22M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.62M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

2_Dense/model.safetensors: reconstructing file:   0%|          |  0.00B / 2.36MB

2_Dense/model.safetensors: downloading bytes:           |  0.00B

synthetic_fixed  LaBSE                          acc@1=0.5235 nDCG@10=0.6309
heldout_raw      LaBSE                          acc@1=0.4629 nDCG@10=0.5781
belebele         LaBSE                          acc@1=0.4433 nDCG@10=0.5498

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/498k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  471MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

synthetic_fixed  e5-small                       acc@1=0.8294 nDCG@10=0.8916
heldout_raw      e5-small                       acc@1=0.7615 nDCG@10=0.8484
belebele         e5-small                       acc@1=0.4322 nDCG@10=0.5599

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

synthetic_fixed  e5-base                        acc@1=0.8765 nDCG@10=0.9212
heldout_raw      e5-base                        acc@1=0.7695 nDCG@10=0.8545
belebele         e5-base                        acc@1=0.5600 nDCG@10=0.6706

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/160k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/690 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.24GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

synthetic_fixed  e5-large                       acc@1=0.8882 nDCG@10=0.9294
heldout_raw      e5-large                       acc@1=0.8297 nDCG@10=0.9023
belebele         e5-large                       acc@1=0.5522 nDCG@10=0.6883

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.27GB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

synthetic_fixed  bge-m3                         acc@1=0.9294 nDCG@10=0.9577
heldout_raw      bge-m3                         acc@1=0.8537 nDCG@10=0.9193
belebele         bge-m3                         acc@1=0.7944 nDCG@10=0.8659

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/17.2k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.19GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/9.71k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

synthetic_fixed  Qwen3-Embedding-0.6B           acc@1=0.7941 nDCG@10=0.8666
heldout_raw      Qwen3-Embedding-0.6B           acc@1=0.6774 nDCG@10=0.7708
belebele         Qwen3-Embedding-0.6B           acc@1=0.5433 nDCG@10=0.6340
skip EmbeddingGemma-300m: 401 Client Error. (Request ID: Root=1-6ac5ed9a-4f7256ca7489bf25144d012c;0550fe11-0be8-47d8-a101-31a20ed2debb)

Cannot access gated repo for url https:

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

synthetic_fixed  ours: e5-base FT (hard negs)   acc@1=0.9176 nDCG@10=0.9504
heldout_raw      ours: e5-base FT (hard negs)   acc@1=0.8036 nDCG@10=0.8798
belebele         ours: e5-base FT (hard negs)   acc@1=0.7344 nDCG@10=0.8104

benchmark                     belebele  heldout_raw  synthetic_fixed
model
BM25                             0.484        0.613            0.729
LaBSE                            0.443        0.463            0.524
Qwen3-Embedding-0.6B             0.543        0.677            0.794
bge-m3                           0.794        0.854            0.929
e5-base                          0.560        0.770            0.876
e5-large                         0.552        0.830            0.888
e5-small                         0.432        0.762            0.829
ours: e5-base FT (hard negs)     0.734        0.804            0.918

## Per-query results and agreement analysis

For RQ1 we need per-query outcomes, not only averages: they allow bootstrap confidence intervals for every metric, for Kendall's τ between test sets, and for pairwise system comparisons. The first cell stores the rank of the gold passage for every (test set, system, query) in `results_per_query.csv`; the second computes the agreement statistics from that file.

In [2]:
# Per-query evaluation: rank of the gold passage (1..100, 0 = not in top 100) for every (benchmark, system, query).
# Self-contained apart from `heldout_chunks` (held-out generation cell). Saves after each system and resumes:
# systems already in results_per_query.csv are skipped.
!pip install -q rank_bm25 "sentence-transformers>=6.0.1"
import re, gc, os, json, random, torch, numpy as np, pandas as pd
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from datasets import load_dataset

norm = lambda t: " ".join(t.split())
tok = lambda t: re.findall(r'\w+', t.lower())
B = {}  # benchmark -> (corpus {doc_id: text}, queries {qid: (text, gold_doc_id, style)})

# 1. Synthetic test (170 queries), corrected corpus: gold duplicates removed from distractors
ds = load_dataset("Zhantas/Cleaned-Kyrgyz_Wikipedia", split="train")
chunks = [{"title": a["title"], "text": p.strip()} for a in ds.select(range(5000))
          for p in a["text"].split("\n") if 200 < len(p) < 800]
data = json.load(open("/content/drive/MyDrive/pairs_raw_v2.json", encoding="utf-8"))
seen, uniq = set(), []
for p in data:
    if p["positive"] not in seen:
        seen.add(p["positive"]); uniq.append(p)
random.seed(42); random.shuffle(uniq)
test_pairs = uniq[int(len(uniq) * 0.9):]
gold = {norm(p["positive"]) for p in test_pairs}
corpus = {f"w{i}": c["text"] for i, c in enumerate(chunks[:5000]) if norm(c["text"]) not in gold}
qs = {}
for qi, p in enumerate(test_pairs):
    corpus[f"g{qi}"] = p["positive"]; qs[str(qi)] = (p["query"], f"g{qi}", "question")
B["synthetic"] = (corpus, qs)

# 2. Held-out LLM test (single generator), articles never used in training
ho = json.load(open(HELDOUT_PATH, encoding="utf-8"))
hg = {norm(t["positive"]) for t in ho}
corpus = {f"d{i}": c["text"] for i, c in enumerate([c for c in heldout_chunks if norm(c["text"]) not in hg][:5000])}
qs = {}
for t in ho:
    corpus[f"g{t['id']}"] = t["positive"]; qs[str(t["id"])] = (t["query"], f"g{t['id']}", t["style"])
B["heldout_llm"] = (corpus, qs)

# 3. Belebele kir_Cyrl: human-written questions, FLORES passages + Wikipedia distractors
bele = load_dataset("facebook/belebele", "kir_Cyrl", split="test")
passages = sorted({ex["flores_passage"] for ex in bele})
pid = {p: f"b{i}" for i, p in enumerate(passages)}
corpus = {pid[p]: p for p in passages}
corpus.update({f"w{i}": c["text"] for i, c in enumerate(chunks[:5000])})
B["belebele"] = (corpus, {str(i): (ex["question"], pid[ex["flores_passage"]], "question") for i, ex in enumerate(bele)})
print({b: (len(c), len(q)) for b, (c, q) in B.items()})

SYSTEMS = {  # name: (model path, query prompt_name, document prompt_name)
    "LaBSE": ("sentence-transformers/LaBSE", None, None),
    "e5-small": ("intfloat/multilingual-e5-small", None, None),
    "e5-base": ("intfloat/multilingual-e5-base", None, None),
    "e5-large": ("intfloat/multilingual-e5-large", None, None),
    "bge-m3": ("BAAI/bge-m3", None, None),
    "Qwen3-Embedding-0.6B": ("Qwen/Qwen3-Embedding-0.6B", "query", None),
    "EmbeddingGemma-300m": ("google/embeddinggemma-300m", "query", "document"),
    "e5-base FT random negs": ("/content/drive/MyDrive/ky-e5-base-v2", None, None),
    "e5-base FT hard negs": ("/content/drive/MyDrive/ky-e5-base-hardneg", None, None),
}
OUT_PQ = "/content/drive/MyDrive/results_per_query.csv"
rows = pd.read_csv(OUT_PQ, dtype={"qid": str}).to_dict("records") if os.path.exists(OUT_PQ) else []
done = {r["system"] for r in rows}
print("already done:", sorted(done))

def gold_ranks(scores, doc_ids, golds, k=100):
    doc_ids = np.array(doc_ids)
    top = np.argsort(-scores, axis=1)[:, :k]
    ranks = []
    for i, g in enumerate(golds):
        hit = np.where(doc_ids[top[i]] == g)[0]
        ranks.append(int(hit[0]) + 1 if len(hit) else 0)
    return ranks

def record(bench, system, ranks):
    for (q, (_, _, style)), r in zip(B[bench][1].items(), ranks):
        rows.append({"benchmark": bench, "system": system, "qid": q, "style": style, "rank": r})

if "BM25" not in done:
    for bench, (corpus, qs) in B.items():
        ids = list(corpus); bm = BM25Okapi([tok(corpus[d]) for d in ids])
        scores = np.array([bm.get_scores(tok(text)) for text, _, _ in qs.values()])
        record(bench, "BM25", gold_ranks(scores, ids, [g for _, g, _ in qs.values()]))

for name, (path, qp, dp) in SYSTEMS.items():
    if name in done:
        continue
    try:
        model = SentenceTransformer(path, model_kwargs={"torch_dtype": torch.float16})
    except Exception as e:
        print(f"skip {name}: {str(e)[:120]}"); continue
    model.max_seq_length = 512
    for bench, (corpus, qs) in B.items():
        ids = list(corpus)
        D = model.encode([corpus[d] for d in ids], batch_size=64, normalize_embeddings=True, prompt_name=dp, convert_to_numpy=True)
        Q = model.encode([text for text, _, _ in qs.values()], batch_size=64, normalize_embeddings=True, prompt_name=qp, convert_to_numpy=True)
        record(bench, name, gold_ranks(Q @ D.T, ids, [g for _, g, _ in qs.values()]))
    del model; gc.collect(); torch.cuda.empty_cache()
    pd.DataFrame(rows).to_csv(OUT_PQ, index=False)
    print("done", name)

pq = pd.DataFrame(rows); pq.to_csv(OUT_PQ, index=False)
pq["acc@1"] = (pq["rank"] == 1).astype(float)
display(pq.pivot_table(index="system", columns="benchmark", values="acc@1").round(3))

{'synthetic': (5112, 170), 'heldout_llm': (5499, 499), 'belebele': (5488, 900)}
already done: ['BM25', 'LaBSE', 'Qwen3-Embedding-0.6B', 'bge-m3', 'e5-base', 'e5-base FT random negs', 'e5-large', 'e5-small']
skip EmbeddingGemma-300m: 401 Client Error. (Request ID: Root=1-6ac8ad18-471727101d267e2b540b50b6;e85e8fd3-51e6-4e4b-b109-14c9f59836bd)

Cannot ac

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

done e5-base FT hard negs

benchmark               belebele  heldout_llm  synthetic
system
BM25                       0.484        0.667      0.735
LaBSE                      0.444        0.489      0.524
Qwen3-Embedding-0.6B       0.543        0.715      0.794
bge-m3                     0.793        0.884      0.929
e5-base                    0.564        0.808      0.876
e5-base FT hard negs       0.734        0.822      0.918
e5-base FT random negs     0.738        0.812      0.900
e5-large                   0.548        0.856      0.888
e5-small                   0.430        0.790      0.829

In [3]:
# Agreement analysis from per-query results (no GPU needed).
#   - metric per system and test set, with 95% bootstrap intervals over queries
#   - Kendall's tau between the system rankings of two test sets, with a bootstrap interval
#   - pairwise order: for each system pair, is A > B significant on each test set, and does it flip between sets?
import itertools, numpy as np, pandas as pd
from scipy.stats import kendalltau

pq = pd.read_csv("/content/drive/MyDrive/results_per_query.csv", dtype={"qid": str})
pq["acc@1"] = (pq["rank"] == 1).astype(float)
pq["ndcg@10"] = np.where(pq["rank"].between(1, 10), 1 / np.log2(pq["rank"].clip(lower=1) + 1), 0.0)
N_BOOT, rng = 1000, np.random.default_rng(0)

def matrix(bench, metric, style=None):
    d = pq[(pq.benchmark == bench) & ((pq["style"] == style) if style else True)]
    return d.pivot(index="system", columns="qid", values=metric)

def boot_means(m):  # systems x N_BOOT bootstrap means (queries resampled, same resample for all systems)
    X = m.values
    idx = rng.integers(0, X.shape[1], (N_BOOT, X.shape[1]))
    return np.stack([X[:, i].mean(1) for i in idx], axis=1)

def summary(metric):
    out = {}
    for bench in pq.benchmark.unique():
        m = matrix(bench, metric); bm = boot_means(m)
        lo, hi = np.percentile(bm, [2.5, 97.5], axis=1)
        out[bench] = [f"{v:.3f} [{l:.3f}, {h:.3f}]" for v, l, h in zip(m.values.mean(1), lo, hi)]
        idx = m.index
    return pd.DataFrame(out, index=idx)

def tau(b1, b2, metric, style1=None, style2=None):
    m1, m2 = matrix(b1, metric, style1), matrix(b2, metric, style2)
    s = m1.index.intersection(m2.index); m1, m2 = m1.loc[s], m2.loc[s]
    point = kendalltau(m1.values.mean(1), m2.values.mean(1))[0]
    boots = [kendalltau(a, b)[0] for a, b in zip(boot_means(m1).T, boot_means(m2).T)]
    return point, *np.percentile(boots, [2.5, 97.5]), len(s)

def significant_order(bench, metric):  # {(A, B): +1 if A > B significantly, -1 if A < B, 0 if not separable}
    m = matrix(bench, metric); bm = boot_means(m); names = list(m.index); out = {}
    for i, j in itertools.combinations(range(len(names)), 2):
        lo, hi = np.percentile(bm[i] - bm[j], [2.5, 97.5])
        out[(names[i], names[j])] = 1 if lo > 0 else -1 if hi < 0 else 0
    return out

for metric in ("ndcg@10", "acc@1"):
    print(f"\n=== {metric}: mean [95% CI] ==="); display(summary(metric))
    print(f"Kendall's tau between test sets ({metric}):")
    for b1, b2 in [("synthetic", "heldout_llm"), ("synthetic", "belebele"), ("heldout_llm", "belebele")]:
        t, lo, hi, n = tau(b1, b2, metric)
        print(f"  {b1:12s} vs {b2:12s} tau = {t:.2f} [{lo:.2f}, {hi:.2f}]  ({n} systems)")
    o = {b: significant_order(b, metric) for b in ("heldout_llm", "belebele")}
    flips = [p for p in o["belebele"] if o["heldout_llm"][p] * o["belebele"][p] == -1]
    differ = [p for p in o["belebele"] if o["heldout_llm"][p] != o["belebele"][p]]
    print(f"  system pairs: {len(o['belebele'])}; significant opposite order held-out vs Belebele: {len(flips)} {flips}")
    print(f"  pairs whose significant order differs at all: {len(differ)}")

print("\nHeld-out by query style (nDCG@10, tau question vs keywords):", tau("heldout_llm", "heldout_llm", "ndcg@10", "question", "keywords"))

=== ndcg@10: mean [95% CI] ===

,synthetic,heldout_llm,belebele
system,,,
BM25,"0.814 [0.763, 0.863]","0.769 [0.737, 0.803]","0.572 [0.542, 0.600]"
LaBSE,"0.631 [0.569, 0.696]","0.602 [0.564, 0.639]","0.550 [0.521, 0.579]"
Qwen3-Embedding-0.6B,"0.867 [0.825, 0.909]","0.803 [0.775, 0.832]","0.634 [0.606, 0.662]"
bge-m3,"0.956 [0.930, 0.980]","0.936 [0.920, 0.953]","0.865 [0.847, 0.884]"
e5-base,"0.922 [0.887, 0.955]","0.879 [0.856, 0.902]","0.673 [0.645, 0.700]"
e5-base FT hard negs,"0.950 [0.922, 0.974]","0.895 [0.874, 0.915]","0.810 [0.788, 0.834]"
e5-base FT random negs,"0.941 [0.913, 0.967]","0.887 [0.864, 0.908]","0.807 [0.784, 0.830]"
e5-large,"0.929 [0.895, 0.959]","0.917 [0.899, 0.937]","0.686 [0.661, 0.712]"
e5-small,"0.892 [0.851, 0.928]","0.867 [0.844, 0.892]","0.559 [0.532, 0.589]"

Kendall's tau between test sets (ndcg@10):
  synthetic    vs heldout_llm  tau = 0.89 [0.67, 0.94]  (9 systems)
  synthetic    vs belebele     tau = 0.89 [0.67, 0.94]  (9 systems)
  heldout_llm  vs belebele     tau = 0.78 [0.61, 0.83]  (9 systems)
  system pairs: 36; significant opposite order held-out vs Belebele: 3 [('Qwen3-Embedding-0.6B', 'e5-small'), ('e5-base FT hard negs', 'e5-large'), ('e5-base FT random negs', 'e5-large')]
  pairs whose significant order differs at all: 9

=== acc@1: mean [95% CI] ===

,synthetic,heldout_llm,belebele
system,,,
BM25,"0.735 [0.665, 0.800]","0.667 [0.625, 0.707]","0.484 [0.450, 0.516]"
LaBSE,"0.524 [0.447, 0.600]","0.489 [0.449, 0.535]","0.444 [0.413, 0.478]"
Qwen3-Embedding-0.6B,"0.794 [0.729, 0.853]","0.715 [0.673, 0.754]","0.543 [0.513, 0.576]"
bge-m3,"0.929 [0.894, 0.965]","0.884 [0.856, 0.910]","0.793 [0.768, 0.821]"
e5-base,"0.876 [0.824, 0.924]","0.808 [0.770, 0.840]","0.564 [0.531, 0.598]"
e5-base FT hard negs,"0.918 [0.871, 0.953]","0.822 [0.788, 0.854]","0.734 [0.707, 0.762]"
e5-base FT random negs,"0.900 [0.853, 0.941]","0.812 [0.776, 0.844]","0.738 [0.712, 0.764]"
e5-large,"0.888 [0.841, 0.935]","0.856 [0.824, 0.886]","0.548 [0.517, 0.581]"
e5-small,"0.829 [0.771, 0.882]","0.790 [0.749, 0.824]","0.430 [0.399, 0.462]"

Kendall's tau between test sets (acc@1):
  synthetic    vs heldout_llm  tau = 0.89 [0.61, 0.97]  (9 systems)
  synthetic    vs belebele     tau = 0.72 [0.50, 0.86]  (9 systems)
  heldout_llm  vs belebele     tau = 0.61 [0.42, 0.72]  (9 systems)
  system pairs: 36; significant opposite order held-out vs Belebele: 4 [('BM25', 'e5-small'), ('Qwen3-Embedding-0.6B', 'e5-small'), ('e5-base FT hard negs', 'e5-large'), ('e5-base FT random negs', 'e5-large')]
  pairs whose significant order differs at all: 14

Held-out by query style (nDCG@10, tau question vs keywords): (np.float64(0.8888888888888888), np.float64(0.6666666666666666), np.float64(1.0), 9)

In [5]:
# Generator pilot: 20 passages, query from an open-weight model vs. the existing Gemini query.
# Open model: gpt-oss-120b via Groq free tier (can later run locally on the GPU server).
# Output is a blind side-by-side sheet: A/B order is randomised per row; the key is saved separately.
import random, pandas as pd
PILOT_MODEL = "openai/gpt-oss-120b"
items = json.load(open(HELDOUT_PATH, encoding="utf-8"))
excluded = set(json.load(open("/content/drive/MyDrive/annotation/assignments.json"))["excluded_examples"])
rng = random.Random(11)
pool = [t for t in items if t["id"] not in excluded]
sample = rng.sample([t for t in pool if t["style"] == "question"], 10) + rng.sample([t for t in pool if t["style"] == "keywords"], 10)

rows, key = [], []
for t in sample:
    for attempt in range(5):
        try:
            r = groq.chat.completions.create(model=PILOT_MODEL, max_tokens=1024,
                    messages=[{"role": "user", "content": PROMPTS[t["style"]].format(text=t["positive"])}])
            open_q = (r.choices[0].message.content or "").strip()
            break
        except Exception as e:
            print("retry:", str(e)[:100]); time.sleep(20)
    else:
        print("giving up at", len(rows)); break
    pair = [("gemini", t["query"]), (PILOT_MODEL, open_q)]
    rng.shuffle(pair)
    rows.append({"id": t["id"], "style": t["style"], "passage": t["positive"], "query_A": pair[0][1], "query_B": pair[1][1],
                 "better (A/B/same)": "", "A_ok (1/0)": "", "B_ok (1/0)": "", "note": ""})
    key.append({"id": t["id"], "A": pair[0][0], "B": pair[1][0]})
    time.sleep(2)

pd.DataFrame(rows).to_csv("/content/drive/MyDrive/annotation/generator_pilot_blind.csv", index=False, encoding="utf-8-sig")
pd.DataFrame(key).to_csv("/content/drive/MyDrive/generator_pilot_KEY_do_not_open.csv", index=False)
print(f"{len(rows)} rows written")

20 rows written